name: Front Docker Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  front-build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:time_manager_front"
        file: ./Dockerfile
        push: true
        tags: aminhelloworld/timemanager-front:latest

  back-build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: "{{defaultContext}}:time_manager"
        file: ./Dockerfile
        push: true
        tags: aminhelloworld/timemanager-back:latest


  deploy:
    needs: [front-build-and-push, back-build-and-push]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      run: echo "Deploying to production..."