name: Docker Build and Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: hanenetriaa

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./time_manager
        file: ./time_manager/Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/time_manager:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./time_manager_front
        file: ./time_manager_front/Dockerfile
        push: true
        tags: ${{ env.DOCKER_HUB_USERNAME }}/time_manager_frontend:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
